<%@ Page Language="C#" AutoEventWireup="true" CodeFile="CadastroMenu.aspx.cs" Inherits="CadastroMenu" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body background="imagens/fundo7.jpg" style="float: right">
    <form id="form1" runat="server">
    <div>
        <div style="width: 738px; height: 44px; background-color: white">
            <div style="padding-left: 8px; float: left; width: 343px; padding-top: 12px; height: 27px">
                <span style="font-size: 14pt; color: #ff0000"><strong>
        Gerador de Menus</strong></span></div>
            <div style="float: right; width: 68px; padding-top: 15px; height: 31px; text-align: center">
                <asp:LinkButton ID="lbtnLogout" runat="server" OnClick="lbtnLogout_Click">Logout</asp:LinkButton></div>
            <div style="float: right; width: 86px; padding-top: 15px; height: 31px; text-align: center">
                <asp:ImageButton ID="ImageButton1" runat="server" ImageUrl="~/imagens/voltar.jpg"
                    OnClick="ImageButton1_Click" /></div>
        </div>
        <br />
        <div style="float: left; width: 228px; height: 335px; overflow: auto;">
            <asp:TreeView ID="trvMenu" runat="server" Font-Bold="True" AutoGenerateDataBindings="False" Height="62px" Width="200px" ForeColor="White" >
                <SelectedNodeStyle BackColor="Red" />
            </asp:TreeView>
        </div>
        <div style="width: 504px; height: 200px; color: #000000;">
            &nbsp;&nbsp;
            <br />
            <table>
                <tr>
                    <td colspan="2" style="height: 36px; background-color: #ffcc00; text-align: center">
                        <asp:Button ID="btnNovoMenu" runat="server" Text="Novo Menu" OnClick="btnNovoMenu_Click" />
            <asp:Button ID="btnNovoSubMenu" runat="server" Text="Novo Sub-Menu" OnClick="btnNovoSubMenu_Click" />
            <asp:Button ID="btnExcluir" runat="server" OnClick="btnExcluir_Click" Text="Excluir"
                Width="130px" />&nbsp;
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="width: 196px; background-color: white">
                    </td>
                </tr>
                <tr>
                    <td style="width: 196px; background-color: white;">
                        Nome</td>
                    <td style="width: 196px; background-color: white;">
                        <asp:TextBox ID="txtNome" runat="server" Width="369px" BackColor="White"></asp:TextBox></td>
                </tr>
                <tr>
                    <td style="width: 196px; background-color: white;">
                        URL</td>
                    <td style="width: 196px; background-color: white;">
                        <asp:TextBox ID="txtURL" runat="server" Width="369px" BackColor="White"></asp:TextBox></td>
                </tr>
                <tr>
                    <td style="width: 196px; background-color: white;">
                        Imagem</td>
                    <td style="width: 196px; background-color: white;">
                        <asp:FileUpload ID="fupImagem" runat="server" Width="370px" BackColor="White" /></td>
                </tr>
                <tr>
                    <td colspan="2" style="text-align: center; height: 36px; background-color: #ffcc00;">
                        <asp:Button ID="btnSalvar" runat="server" OnClick="btnSalvar_Click" Text="Salvar"
                            Width="85px" />
                        <asp:Button ID="btnCancelar" runat="server" Text="Cancelar" Width="90px" /></td>
                </tr>
                <tr>
                    <td colspan="2" style="height: 50px; background-color: #ffff99; text-align: center">
        <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Gravar no banco de dados"
            Width="179px" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="height: 50px; background-color: #ff3300; text-align: center">
        <asp:LinkButton ID="LinkButton1" runat="server" PostBackUrl="~/MenuDinamico.aspx" Width="250px" Font-Bold="True" Font-Size="14pt">Testar o menu cadastrado</asp:LinkButton></td>
                </tr>
            </table>
        </div>
        <br />
    
    </div>
        &nbsp;<br />
        <br />
    </form>
</body>
</html>
