<%@ Page Language="C#" MasterPageFile="~/Principal.master" AutoEventWireup="true" CodeFile="MenuGrupo.aspx.cs" Inherits="MenuGrupo" Title="Untitled Page" %>
<%@ MasterType VirtualPath="~/Principal.master"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div style="float: right; width: 344px; height: 239px; text-align: left; background-color: #ffffcc;">
        &nbsp;<asp:TreeView ID="trvMenu" runat="server" AutoGenerateDataBindings="False"
            Font-Bold="True" Height="204px" Width="290px" Enabled="False" LineImagesFolder="~/TreeLineImages" OnTreeNodeCheckChanged="trvMenu_TreeNodeCheckChanged" ShowCheckBoxes="All" ShowLines="True">
        </asp:TreeView>
    </div>
    <div style="width: 404px; height: 241px; text-align: left; background-color: #ffffcc;">
        <asp:GridView ID="grvGrupos" runat="server" AutoGenerateColumns="False" BackColor="LightGoldenrodYellow"
            BorderColor="Tan" BorderWidth="1px" CellPadding="2" ForeColor="Black" GridLines="Vertical"
            OnPageIndexChanging="grvGrupos_PageIndexChanging" DataKeyNames="CodGrupo" OnSelectedIndexChanged="grvGrupos_SelectedIndexChanged">
            <FooterStyle BackColor="Tan" />
            <Columns>
                <asp:BoundField DataField="CodGrupo" HeaderText="C&#243;digo" />
                <asp:BoundField DataField="Descricao" HeaderText="Descri&#231;&#227;o">
                    <ItemStyle Width="300px" />
                </asp:BoundField>
                <asp:CommandField HeaderText="Selecionar" SelectText="Selecionar" ShowSelectButton="True" />
            </Columns>
            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <HeaderStyle BackColor="Tan" Font-Bold="True" />
            <AlternatingRowStyle BackColor="PaleGoldenrod" />
        </asp:GridView>
    </div>
</asp:Content>

